// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oykikvsztqgpfrszmngr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95a2lrdnN6dHFncGZyc3ptbmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODUyMTMsImV4cCI6MjA2NjU2MTIxM30.3lKMSj6bT8SNqheKX71nuivnXwMO0MYX2EQRD5cfc2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);